package com.hwpp.mod;

import dev.isxander.yacl3.api.*;
import dev.isxander.yacl3.api.controller.BooleanControllerBuilder;
import dev.isxander.yacl3.api.controller.IntegerSliderControllerBuilder;
import dev.isxander.yacl3.api.controller.IntegerFieldControllerBuilder;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;

public class ModConfigScreen {
	public static Screen create(Screen parent) {
		return YetAnotherConfigLib.createBuilder()
			.title(Component.translatable("hwopt.config.title"))
			.category(ConfigCategory.createBuilder()
				.name(Component.translatable("hwopt.config.category.rendering"))
				.group(OptionGroup.createBuilder()
					.name(Component.translatable("hwopt.config.group.entityCulling"))
					.collapsed(false)
					.option(Option.<Boolean>createBuilder()
						.name(Component.translatable("hwopt.config.tickCulling"))
						.description(OptionDescription.of(Component.translatable("hwopt.config.tickCulling.desc")))
						.binding(true, () -> Config.get().tickCulling, v -> Config.get().tickCulling = v)
						.controller(opt -> BooleanControllerBuilder.create(opt))
						.build())
					.option(Option.<Boolean>createBuilder()
						.name(Component.translatable("hwopt.config.blockEntityCulling"))
						.binding(true, () -> Config.get().blockEntityCulling, v -> Config.get().blockEntityCulling = v)
						.controller(opt -> BooleanControllerBuilder.create(opt))
						.build())
					.option(Option.<Boolean>createBuilder()
						.name(Component.translatable("hwopt.config.solidLeaves"))
						.binding(false, () -> Config.get().solidLeaves, v -> Config.get().solidLeaves = v)
						.controller(opt -> BooleanControllerBuilder.create(opt))
						.build())
					.option(Option.<Boolean>createBuilder()
						.name(Component.translatable("hwopt.config.nametagsThroughWalls"))
						.binding(false, () -> Config.get().nametagsThroughWalls, v -> Config.get().nametagsThroughWalls = v)
						.controller(opt -> BooleanControllerBuilder.create(opt))
						.build())
					.option(Option.<Integer>createBuilder()
						.name(Component.translatable("hwopt.config.tracingDistance"))
						.binding(128, () -> Config.get().tracingDistance, v -> Config.get().tracingDistance = v)
						.controller(opt -> IntegerSliderControllerBuilder.create(opt)
							.range(16, 512)
							.step(16))
						.build())
					.build())
				.group(OptionGroup.createBuilder()
					.name(Component.translatable("hwopt.config.group.particle"))
					.collapsed(false)
					.option(Option.<Boolean>createBuilder()
						.name(Component.translatable("hwopt.config.asyncParticleTick"))
						.binding(true, () -> Config.get().asyncParticleTick, v -> Config.get().asyncParticleTick = v)
						.controller(opt -> BooleanControllerBuilder.create(opt))
						.build())
					.build())
				.build())
			.category(ConfigCategory.createBuilder()
				.name(Component.translatable("hwopt.config.category.network"))
				.group(OptionGroup.createBuilder()
					.name(Component.translatable("hwopt.config.group.aggregation"))
					.collapsed(false)
					.option(Option.<Integer>createBuilder()
						.name(Component.translatable("hwopt.config.netFlushMs"))
						.binding(20, () -> Config.get().netFlushMs, v -> Config.get().netFlushMs = v)
						.controller(opt -> IntegerSliderControllerBuilder.create(opt).range(5, 100).step(5))
						.build())
					.option(Option.<Integer>createBuilder()
						.name(Component.translatable("hwopt.config.netMaxBytes"))
						.binding(262144, () -> Config.get().netMaxBytes, v -> Config.get().netMaxBytes = v)
						.controller(opt -> IntegerSliderControllerBuilder.create(opt).range(16384, 1048576).step(16384))
						.build())
					.option(Option.<Integer>createBuilder()
						.name(Component.translatable("hwopt.config.netMaxCount"))
						.binding(50, () -> Config.get().netMaxCount, v -> Config.get().netMaxCount = v)
						.controller(opt -> IntegerSliderControllerBuilder.create(opt).range(5, 200).step(5))
						.build())
					.option(Option.<Integer>createBuilder()
						.name(Component.translatable("hwopt.config.netMaxPacketSize"))
						.binding(4194304, () -> Config.get().netMaxPacketSize, v -> Config.get().netMaxPacketSize = v)
						.controller(opt -> IntegerSliderControllerBuilder.create(opt).range(262144, 16777216).step(262144))
						.build())
					.build())
				.group(OptionGroup.createBuilder()
					.name(Component.translatable("hwopt.config.group.dcc"))
					.collapsed(false)
					.option(Option.<Integer>createBuilder()
						.name(Component.translatable("hwopt.config.dccCacheTimeout"))
						.binding(60, () -> Config.get().dccCacheTimeout, v -> Config.get().dccCacheTimeout = v)
						.controller(opt -> IntegerSliderControllerBuilder.create(opt).range(10, 300).step(10))
						.build())
					.option(Option.<Integer>createBuilder()
						.name(Component.translatable("hwopt.config.dccCacheDistance"))
						.binding(8, () -> Config.get().dccCacheDistance, v -> Config.get().dccCacheDistance = v)
						.controller(opt -> IntegerSliderControllerBuilder.create(opt).range(2, 32).step(2))
						.build())
					.option(Option.<Integer>createBuilder()
						.name(Component.translatable("hwopt.config.dccBufferDistance"))
						.binding(8, () -> Config.get().dccBufferDistance, v -> Config.get().dccBufferDistance = v)
						.controller(opt -> IntegerSliderControllerBuilder.create(opt).range(2, 32).step(2))
						.build())
					.build())
				.build())
			.category(ConfigCategory.createBuilder()
				.name(Component.translatable("hwopt.config.category.world"))
				.group(OptionGroup.createBuilder()
					.name(Component.translatable("hwopt.config.group.world"))
					.option(Option.<Boolean>createBuilder()
						.name(Component.translatable("hwopt.configuration.world.spawnAtVillage"))
						.description(OptionDescription.of(Component.translatable("hwopt.configuration.world.spawnAtVillage.tooltip")))
						.binding(false, () -> Config.get().spawnAtVillage, v -> Config.get().spawnAtVillage = v)
						.controller(opt -> BooleanControllerBuilder.create(opt))
						.build())
					.build())
				.build())
			.category(ConfigCategory.createBuilder()
				.name(Component.translatable("hwopt.config.category.debug"))
				.group(OptionGroup.createBuilder()
					.name(Component.translatable("hwopt.config.group.debug"))
					.option(Option.<Boolean>createBuilder()
						.name(Component.translatable("hwopt.configuration.debug.logChunkGen"))
						.description(OptionDescription.of(Component.translatable("hwopt.configuration.debug.logChunkGen.tooltip")))
						.binding(false, () -> Config.get().logChunkGen, v -> Config.get().logChunkGen = v)
						.controller(opt -> BooleanControllerBuilder.create(opt))
						.build())
					.option(Option.<Integer>createBuilder()
						.name(Component.translatable("hwopt.configuration.debug.logChunkGenInterval"))
						.binding(0, () -> Config.get().logChunkGenInterval, v -> Config.get().logChunkGenInterval = v)
						.controller(opt -> IntegerFieldControllerBuilder.create(opt))
						.build())
					.build())
				.build())
			.save(Config::save)
			.build()
			.generateScreen(parent);
	}
}
